# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test-generate-social-image-cmd',
                'doc_host': 'https://harishmohanraj.github.io',
                'git_url': 'https://github.com/harishmohanraj/test-generate-social-image-cmd',
                'lib_path': 'test_generate_social_image_cmd'},
  'syms': { 'test_generate_social_image_cmd.core': { 'test_generate_social_image_cmd.core.foo': ( 'core.html#foo',
                                                                                                  'test_generate_social_image_cmd/core.py')}}}
